blank_issues_enabled: false
contact_links:
  - name: 'Report security issue'
    url: 'https://github.com/lucianoedipo/react-lgpd-consent/issues/new?assignees=&labels=security&template=bug_report.md&title=%5BSECURITY%5D'
    about: 'Use this to report security-sensitive issues (avoid posting secrets).'
