# .github/workflows/package-check.yml
name: Package Check
on:
  pull_request:

jobs:
  pack:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v5
        with:
          node-version: 20
          cache: npm
          cache-dependency-path: package-lock.json
      - name: Pin npm 10 to avoid npm@11 CI bug
        run: npm i -g npm@10.9.0
      - name: Show Node/npm versions
        run: |
          node -v
          npm -v
      - name: Configure npm (stability)
        run: |
          npm config set audit false
          npm config set fund false
          npm config set progress false
          npm config set prefer-offline false
          npm config set engine-strict false
      - name: Clean npm cache
        run: npm cache clean --force
      - name: Install dependencies (ci with fallback)
        run: |
          npm ci --no-audit --no-fund --ignore-scripts || npm install --no-audit --no-fund --ignore-scripts --legacy-peer-deps
      - name: Build
        run: npm run build
      - name: Pack package
        run: npm pack --json > pack.json
      - name: Exibir arquivos do tarball
        run: node -e "console.log(JSON.parse(require('fs').readFileSync('pack.json','utf8'))[0].files.map(f=>f.path).join('\n'))"
