# .github/workflows/package-check.yml
name: Package Check
on:
  pull_request:

jobs:
  pack:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v5
        with:
          node-version: 20
          cache: npm
          cache-dependency-path: package-lock.json
      - name: Enable Corepack
        run: corepack enable
      - name: Use npm version from package.json (corepack)
        run: corepack prepare npm@11.6.1 --activate
      - name: Clean install (npm install)
        run: npm install --no-audit --no-fund --ignore-scripts
      - name: Build
        run: npm run build
      - name: Pack package
        run: npm pack --json > pack.json
      - name: Exibir arquivos do tarball
        run: node -e "console.log(JSON.parse(require('fs').readFileSync('pack.json','utf8'))[0].files.map(f=>f.path).join('\n'))"
