# .github/workflows/package-check.yml
name: Package Check
on:
  pull_request:

jobs:
  pack:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      
      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10
      
      - uses: actions/setup-node@v5
        with:
          node-version: 20
          cache: pnpm
      
      - name: Cache TypeScript builds
        uses: actions/cache@v4
        with:
          path: |
            .tsbuildinfo
            node_modules/.cache
          key: ${{ runner.os }}-typescript-${{ hashFiles('**/tsconfig.json', '**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-typescript-
      
      - name: Show Node/pnpm versions
        run: |
          node -v
          pnpm -v
      
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      
      - name: Build
        run: pnpm run build
      
      - name: Pack package
        run: pnpm pack --json > pack.json
      
      - name: Exibir arquivos do tarball
        run: node -e "console.log(JSON.parse(require('fs').readFileSync('pack.json','utf8'))[0].files.map(f=>f.path).join('\n'))"
