name: Publish package to npmjs

on:
  push:
    tags: ['v*']
  release:
    types: [published]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0 # ensure full history for ancestry checks

      - name: Check tag commit is on main
        id: check_main
        shell: bash
        run: |
          git fetch --no-tags --prune origin +refs/heads/main:refs/remotes/origin/main
          if git merge-base --is-ancestor "$GITHUB_SHA" origin/main; then
            echo "on_main=true" >> "$GITHUB_OUTPUT"
            echo "Tag commit is on main. Proceeding with publish."
          else
            echo "on_main=false" >> "$GITHUB_OUTPUT"
            echo "Tag commit is NOT on main. Skipping publish steps."
          fi

      - name: Install pnpm
        if: steps.check_main.outputs.on_main == 'true'
        uses: pnpm/action-setup@v4
        with:
          version: 10

      - name: Setup Node for npmjs
        uses: actions/setup-node@v5
        with:
          node-version: 20
          registry-url: https://registry.npmjs.org
          cache: pnpm

      - name: Install and build
        if: steps.check_main.outputs.on_main == 'true'
        run: |
          pnpm install --frozen-lockfile
          pnpm run build

      - name: Configure npm auth for publish
        if: steps.check_main.outputs.on_main == 'true'
        run: |
          if [ -z "${{ secrets.NPM_TOKEN }}" ]; then
            echo "NPM_TOKEN not set, skipping npm publish steps"
            exit 0
          fi
          echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" > ~/.npmrc

      - name: Publish to npmjs
        if: steps.check_main.outputs.on_main == 'true'
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          if [ -z "${{ secrets.NPM_TOKEN }}" ]; then
            echo "NPM_TOKEN not set, skipping npm publish"
            exit 0
          fi
          npm publish --access public

      - name: Skipped publish (tag not on main)
        if: steps.check_main.outputs.on_main != 'true'
        run: |
          echo "Publish workflow completed without publishing because the tag commit is not on main."
